### ISSUE TITLE
Deadlock if one listener stops listening

### ISSUE THREAD

**Issue by chabad360** [SierraSoftworks/multicast#3]
There seems to be a flaw where the system can deadlock should one of the listeners stop listening. This effect is rather hard to reproduce, but from a logical analysis seems to be cascading (i.e. it starts with the listener that stops listening, and works it's way up the chain every message).

https://play.golang.org/p/3PMMVwkvHaf
```go
package main

import (
	"fmt"

	"github.com/sierrasoftworks/multicast"
)

func main() {
	c := multicast.New()

	_ = c.Listen()

	go func() {
		l := c.Listen()
		for {
			select {
			case m := <-l.C:
				fmt.Println(m)
			}
		}
	}()

	c.C <- "hello"
	c.C <- "world"
}
```
```
hello
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan send]:
main.main()
	/tmp/sandbox204271500/prog.go:25 +0x10d

goroutine 18 [chan send]:
github.com/sierrasoftworks/multicast.NewListener.func1(0xc000094060, 0xc00009e220, 0xc0000940c0)
	/tmp/gopath860021115/pkg/mod/github.com/sierrasoftworks/multicast@v0.0.0-20190425200731-c029c77710e4/listener.go:26 +0x4d
created by github.com/sierrasoftworks/multicast.NewListener
	/tmp/gopath860021115/pkg/mod/github.com/sierrasoftworks/multicast@v0.0.0-20190425200731-c029c77710e4/listener.go:21 +0x9b

goroutine 19 [chan receive]:
main.main.func1(0xc0000be000)
	/tmp/sandbox204271500/prog.go:18 +0x57
created by main.main
	/tmp/sandbox204271500/prog.go:14 +0xa7

goroutine 20 [chan receive]:
github.com/sierrasoftworks/multicast.NewListener.func1(0xc000094120, 0xc00009e230, 0xc000094180)
	/tmp/gopath860021115/pkg/mod/github.com/sierrasoftworks/multicast@v0.0.0-20190425200731-c029c77710e4/listener.go:22 +0x65
created by github.com/sierrasoftworks/multicast.NewListener
	/tmp/gopath860021115/pkg/mod/github.com/sierrasoftworks/multicast@v0.0.0-20190425200731-c029c77710e4/listener.go:21 +0x9b

Program exited: status 2.

```

This issue was harder to reproduce than expected, as slightly more complicated versions don't execute consistently.  Where I first encountered this error it just stops working but doesn't actually deadlock.

---

One solution I thought of would be to buffer the `out` channel in [`NewListener()`](https://github.com/SierraSoftworks/multicast/blob/c029c77710e4b481bded6cc7b4170e67b3f38528/listener.go#L15-L36), and skip writing to it if it's waiting to be read:

```diff
...
func NewListener(source <-chan interface{}) *Listener {
-	out := make(chan interface{}, 0)
+	out := make(chan interface{}, 1)
	l := &Listener{
		C: out,
	}

	go func() {
		for v := range source {
			if l.f != nil {
				l.f <- v
			}
-			out <- v							    
+			if len(out) == 0 { // only if the channel is empty do we write to it
+				out <- v						    
+			}								    
		}
...
```
---

P.s. the readme example doesn't seem to work.

**Comment by notheotherben** [comment]
Hi @chabad360, thank you for submitting the issue and your PR.

Unfortunately, I believe this behaviour is intentional and I'm not sure that we'd want to change it in this library (but please keep reading for more context on why and what other options you might have).

## Why this is intentional
Consider a "normal" Go channel with a single publisher and a single consumer, something like this:

```go
ch := make(chan int, 0)

go func() {
  // Write the sequence 0..9 to the channel
  for i := 0; i < 10; i++ {
    ch <- i
  }
}

for i := range ch {
  fmt.Println("Got", i)
  time.Sleep(time.Second)
}
```

In this example, we would expect to print out the numbers 0 through 9 at 1 second intervals, because the reader is able to apply backpressure on the channel and limit the rate at which the producer writes to it. This behaviour is an integral feature of CSP and the only safe way to handle writes to channels. Buffering is one way to alleviate this for a period of time (supporting burst-y write-loads) but if your consumer is outpaced by the producer, you will always encounter this blocking behaviour.


## How to drop messages correctly
In your proposal, I see that you've opted to drop messages in situations where a consumer is outpaced by the producer and while that is a perfectly valid decision in some contexts, but in others it may result in undefined behaviour, lost data etc.

Go's channels support the style of write you're talking about here through the following construct (and you should probably use that because the way you're testing whether the channel is empty doesn't guarantee that it will remain so when you then attempt to write to it (remember, you're dealing with a concurrent multithreaded system and Go's channels handle locking for you).

```go
select {
  case ch <- v:
    // The write succeeded because the channel was not full
  default:
    // The write failed because the channel was full
}
```

## Non-blocking `multicast`
If you do want to use this library to provide that non-blocking behaviour, there are a few ways to go about doing it (and which one makes sense for you will depend on how your application is designed).

### 1. Use forwarding proxies
The easiest way to ensure that you don't block the multicast chain (and to allow you to implement your own policies around buffering and dropping of messages) is to use a forwarding proxy.

```go
package main

import (
	"fmt"

	"github.com/sierrasoftworks/multicast"
)

func main() {
	c := multicast.New()

	_ = nonBlockingListener(c)

	go func() {
		l := nonBlockingListener(c)
		for {
			select {
			case m := <-l.C:
				fmt.Println(m)
			}
		}
	}()

	c.C <- "hello"
	c.C <- "world"
}

func nonBlockingListener(c *multicast.Channel) <-chan interface{} {
  ch := make(chan interface{}, 0)
  defer close(ch)

  l := c.Listen()
  for v := range l.C {
    select {
      case ch <- v:
      default:
    }
  }
}
```

### 2. Don't shutdown listeners
To make sure that you don't block subsequent readers, you need to ensure that you never shutdown a listener (or stop consuming from it). A quick way to do this is to make sure that once you're done with your core work, you add a black-hole at the end of your goroutine.

```go
go func() {
  l := c.Listen()
  select {
    case v := <-l.C:
      fmt.Println(v)
  }

  // Discard any new messages
  for _ := range l.C { }
}
```

**Comment by chabad360** [comment]
First of all, thank you very much for your detailed reply (it's like those really long SO answers: way more than I asked for, but now I'll never have to look this up again).

Now, the way I encountered this issue was in a web server where I need to forward a single message (via websocket) to multiple clients. The issue was, if one user reloads their page, because that goroutine is no longer active, its stopped listening, which then effectively kills the whole system. 

In regard to your alternative fix, love it. I did not know you could do that with `select`.
In regards to solution #1, it feels a bit heavy.
In regards to solution #2, I don't know if I want to leave the http handlers open (it's just more memory usage).

Another issue that I noticed that comes out of this, is cleanup, those loose channels are just going to stick around (as there's no way to close just one listener, but if I could do that, it would also solve this issue). I figured I could occasionally tell all the clients to refresh, and right after that, re-initialize the `channel`, allowing the GC to clean up the old stuff.

If you have any other ideas, I'd love to hear them.

**Comment by notheotherben** [comment]
No problem at all, in the situation you're discussing, it sounds like optimizing for minimum overhead on each additional listener is likely not the most important thing in the world (the cost of an open TCP connection and context is likely going to dwarf any overhead there) so maybe a better way to handle this is to have a central distributor.

**WARNING** I've just tossed out the following code without testing it (had about 5 minutes to do so). It probably won't work as written.

```go
type Distributor struct {
  listeners map[string]chan interface{}
  m sync.RWMutex
}

func (d *Distributor) Listen(key string) <-chan interface{} {
  ch := make(chan interface{}, 0)
  m.WLock()
  defer m.WUnlock()

  if och, ok := d.listeners[key]; ok {
    close(och)
  }

  d.listeners[key] = ch
  return ch
}

func (d *Distributor) Close(key string) {
  m.WLock()
  defer m.WUnlock()

  if och, ok := d.listeners[key]; ok {
    close(och)
  }

  delete(d.listeners, key)
}

func (d *Distributor) Publish(v interface{}) {
  m.RLock()
  defer m.RUnlock()

  for _, ch := range d.listeners {
    select {
      case ch <- v:
      default:
    }
  }
}
```

**Comment by chabad360** [comment]
> (the cost of an open TCP connection and context is likely going to dwarf any overhead there)

That's a good point.

Is there any reason why you use a map over a slice?

Also, would you be able to link to this issue in the Readme? I imagine I wouldn't be the first person or the last person who encountered this issue.

**Comment by notheotherben** [comment]
My thought process was that you'd likely want to be able to remove listeners when those HTTP connections are closed, rather than leaving them hanging around. Having the ability to associate each listener with a unique key (perhaps you'd use the connection's remote address, or a unique session identifier?) and remove them when you're done is likely to avoid memory leaks and performance degradation over time in your web service.

Of course, if you're anticipating that you'd never remove these listeners, a slice is also a perfectly acceptable solution.

To be honest, it sounds like maybe adding a variant to this library/another similar one for your usecase and others like it might be the right way to go. Let me put that on my todo list and see what I can toss together.

**Comment by chabad360** [comment]
I figured that was the reason, just wanted to know if there was something in particular that you had in mind.

> To be honest, it sounds like maybe adding a variant to this library/another similar one for your usecase and others like it might be the right way to go. Let me put that on my todo list and see what I can toss together.

Cool, I would really appreciate that. 
Just an idea, how hard would it be to make it that when I run `listener.Close()` it would replace (but that would probably require quite a bit of locking to make it clean) the child listener to the grandparent? Effectively allowing the now closed listener to be GC'd. Or perhaps just use `sync.Once` to start a goroutine that just links the two together, `nil`s `listener.f` and then closes the whole thing.

**Comment by chabad360** [comment]
> WARNING I've just tossed out the following code without testing it (had about 5 minutes to do so). It probably won't work as written.

Yea, about that... It's not working at all (but again, no errors).
https://play.golang.org/p/am2k67dNjVe

**Comment by notheotherben** [comment]
Hmm, after a bit of tweaking I was able to get it working the way I'd expect it to: https://play.golang.org/p/UlLslLMtPcI

Note that I'm using `sync.WaitGroup` to ensure that we don't publish before our goroutines are ready to receive (which would result in the `select { ... }` block dropping the message) and don't exit until after our goroutines have finished receiving (which would result in us not seeing the messages printed before we say "bye").
